//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASO_SERVICIO
    {
        public CASO_SERVICIO()
        {
            this.DETALLE_CASO_SERVICIO = new HashSet<DETALLE_CASO_SERVICIO>();
        }
    
        public string Co_Caso { get; set; }
        public Nullable<int> Co_Solicitud { get; set; }
        public System.DateTime Fe_Caso { get; set; }
        public string Fl_Gasto { get; set; }
        public decimal Ss_Gasto { get; set; }
        public string Fl_Facturado { get; set; }
        public decimal Ss_Facturado { get; set; }
        public string Tx_Estado { get; set; }
        public string Tx_Observaciones { get; set; }
        public string Fl_Informe { get; set; }
        public System.DateTime Fe_RegistroIni { get; set; }
        public string No_UsuarioIni { get; set; }
        public System.DateTime Fe_RegistroMod { get; set; }
        public string No_UsuarioMod { get; set; }
    
        public virtual SOLICITUD_ATENCION SOLICITUD_ATENCION { get; set; }
        public virtual ICollection<DETALLE_CASO_SERVICIO> DETALLE_CASO_SERVICIO { get; set; }
    }
}
