//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.EQUIPO = new HashSet<EQUIPO>();
        }
    
        public int Co_Cliente { get; set; }
        public string Tx_RazonSocial { get; set; }
        public string Nu_Ruc { get; set; }
        public string Tx_Direccion { get; set; }
        public int Co_Distrito { get; set; }
        public string Nu_Telefono { get; set; }
        public string No_NombreContacto { get; set; }
        public string Tx_CargoContacto { get; set; }
        public string Nu_Latitud { get; set; }
        public string Nu_Longitud { get; set; }
    
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual ICollection<EQUIPO> EQUIPO { get; set; }
    }
}
