//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public CONTRATO()
        {
            this.EQUIPO = new HashSet<EQUIPO>();
        }
    
        public int Co_Contrato { get; set; }
        public string No_Contrato { get; set; }
        public string Tx_Tipo { get; set; }
        public System.DateTime Fe_Inicio { get; set; }
        public System.DateTime Fe_Final { get; set; }
        public string Tx_Estado { get; set; }
    
        public virtual ICollection<EQUIPO> EQUIPO { get; set; }
    }
}
