//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_CASO_SERVICIO
    {
        public int Co_Detalle_Caso { get; set; }
        public string Co_Caso { get; set; }
        public int Co_Equipo { get; set; }
        public Nullable<int> Co_Tipo { get; set; }
        public Nullable<System.DateTime> Fe_HoraInicial { get; set; }
        public Nullable<System.DateTime> Fe_HoraFinal { get; set; }
        public Nullable<int> Co_Tecnico { get; set; }
        public string Tx_DetalleServicio { get; set; }
        public string Nu_Error { get; set; }
        public string Fl_Reporte { get; set; }
        public System.DateTime Fe_RegistroIni { get; set; }
        public string No_UsuarioIni { get; set; }
        public System.DateTime Fe_RegistroMod { get; set; }
        public string No_UsuarioMod { get; set; }
    
        public virtual CASO_SERVICIO CASO_SERVICIO { get; set; }
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual TECNICO TECNICO { get; set; }
        public virtual TIPO_SERVICIO TIPO_SERVICIO { get; set; }
    }
}
