//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_SOLICITUD_ATENCION
    {
        public int Co_Solicitud { get; set; }
        public int Co_Equipo { get; set; }
        public string Tx_Problema { get; set; }
        public string Nu_Error { get; set; }
        public string Tx_Observaciones { get; set; }
    
        public virtual EQUIPO EQUIPO { get; set; }
        public virtual SOLICITUD_ATENCION SOLICITUD_ATENCION { get; set; }
    }
}
