//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISTRITO
    {
        public DISTRITO()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.TECNICO = new HashSet<TECNICO>();
        }
    
        public int Co_Distrito { get; set; }
        public string No_Distrito { get; set; }
        public int Co_Provincia { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual PROVINCIA PROVINCIA { get; set; }
        public virtual ICollection<TECNICO> TECNICO { get; set; }
    }
}
