//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO
    {
        public EQUIPO()
        {
            this.DETALLE_CASO_SERVICIO = new HashSet<DETALLE_CASO_SERVICIO>();
            this.DETALLE_SOLICITUD_ATENCION = new HashSet<DETALLE_SOLICITUD_ATENCION>();
            this.LOG_ERROR = new HashSet<LOG_ERROR>();
            this.CONTRATO = new HashSet<CONTRATO>();
        }
    
        public int Co_Equipo { get; set; }
        public string Tx_Modelo { get; set; }
        public string Tx_Marca { get; set; }
        public string Tx_Serie { get; set; }
        public string Tx_Ubicacion { get; set; }
        public int Co_Cliente { get; set; }
        public string Tx_Estado { get; set; }
        public string Tx_Descripcion { get; set; }
        public string Tx_Latitud { get; set; }
        public string Tx_Longitud { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<DETALLE_CASO_SERVICIO> DETALLE_CASO_SERVICIO { get; set; }
        public virtual ICollection<DETALLE_SOLICITUD_ATENCION> DETALLE_SOLICITUD_ATENCION { get; set; }
        public virtual ICollection<LOG_ERROR> LOG_ERROR { get; set; }
        public virtual ICollection<CONTRATO> CONTRATO { get; set; }
    }
}
