//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPS_TECNICO
    {
        public int Co_Gps { get; set; }
        public int Co_Tecnico { get; set; }
        public System.DateTime Fe_Gps { get; set; }
        public string Tx_Latitud { get; set; }
        public string Tx_Longitud { get; set; }
    
        public virtual TECNICO TECNICO { get; set; }
    }
}
