//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD_ATENCION
    {
        public SOLICITUD_ATENCION()
        {
            this.CASO_SERVICIO = new HashSet<CASO_SERVICIO>();
            this.DETALLE_SOLICITUD_ATENCION = new HashSet<DETALLE_SOLICITUD_ATENCION>();
            this.SOLICITUD_COTIZACION = new HashSet<SOLICITUD_COTIZACION>();
        }
    
        public int Co_Solicitud { get; set; }
        public System.DateTime Fe_Solicitud { get; set; }
        public string Tx_Estado { get; set; }
        public string Tx_Observaciones { get; set; }
    
        public virtual ICollection<CASO_SERVICIO> CASO_SERVICIO { get; set; }
        public virtual ICollection<DETALLE_SOLICITUD_ATENCION> DETALLE_SOLICITUD_ATENCION { get; set; }
        public virtual ICollection<SOLICITUD_COTIZACION> SOLICITUD_COTIZACION { get; set; }
    }
}
