//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBUNLIMITEDEntities : DbContext
    {
        public DBUNLIMITEDEntities()
            : base("name=DBUNLIMITEDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CASO_SERVICIO> CASO_SERVICIO { get; set; }
        public DbSet<CLIENTE> CLIENTE { get; set; }
        public DbSet<CONTRATO> CONTRATO { get; set; }
        public DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public DbSet<DETALLE_CASO_SERVICIO> DETALLE_CASO_SERVICIO { get; set; }
        public DbSet<DETALLE_SOLICITUD_ATENCION> DETALLE_SOLICITUD_ATENCION { get; set; }
        public DbSet<DISTRITO> DISTRITO { get; set; }
        public DbSet<EQUIPO> EQUIPO { get; set; }
        public DbSet<GPS_TECNICO> GPS_TECNICO { get; set; }
        public DbSet<LOG_ERROR> LOG_ERROR { get; set; }
        public DbSet<PROVINCIA> PROVINCIA { get; set; }
        public DbSet<SOLICITUD_ATENCION> SOLICITUD_ATENCION { get; set; }
        public DbSet<SOLICITUD_COTIZACION> SOLICITUD_COTIZACION { get; set; }
        public DbSet<TECNICO> TECNICO { get; set; }
        public DbSet<TIPO_SERVICIO> TIPO_SERVICIO { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
    }
}
