//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECNICO
    {
        public TECNICO()
        {
            this.DETALLE_CASO_SERVICIO = new HashSet<DETALLE_CASO_SERVICIO>();
            this.GPS_TECNICO = new HashSet<GPS_TECNICO>();
        }
    
        public int Co_Tecnico { get; set; }
        public string No_Tecnico { get; set; }
        public string Ape_Paterno { get; set; }
        public string Ape_Materno { get; set; }
        public string Tx_NomCompleto { get; set; }
        public string Nu_Dni { get; set; }
        public string Tx_Telefono { get; set; }
        public string Tx_Celular { get; set; }
        public string Tx_Direccion { get; set; }
        public int Co_Distrito { get; set; }
    
        public virtual ICollection<DETALLE_CASO_SERVICIO> DETALLE_CASO_SERVICIO { get; set; }
        public virtual DISTRITO DISTRITO { get; set; }
        public virtual ICollection<GPS_TECNICO> GPS_TECNICO { get; set; }
    }
}
