//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tech.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_SERVICIO
    {
        public TIPO_SERVICIO()
        {
            this.DETALLE_CASO_SERVICIO = new HashSet<DETALLE_CASO_SERVICIO>();
        }
    
        public int Co_Tipo { get; set; }
        public string No_Nombre { get; set; }
        public string Tx_Descripcion { get; set; }
    
        public virtual ICollection<DETALLE_CASO_SERVICIO> DETALLE_CASO_SERVICIO { get; set; }
    }
}
